config/routes.rb
Rails.application.routes.draw do
  if ENV['CATCH_ALL_REDIRECT']
    match '*path', to: redirect(ENV['CATCH_ALL_REDIRECT']), via: :all
  end

  root to: redirect(ENV.fetch('ROOT_REDIRECT', '/register'))

  constraints format: 'html' do
    get '/register', as: 'new_user_profile', to: 'user_profiles#new'
    post '/register', as: 'user_profile', to: 'user_profiles#create'
  end
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_filter :authenticate
  end

  private

  def authenticate
    return unless username? && password?

    authenticate_or_request_with_http_basic do |u, p|
      u == username && p == password
    end
  end

  def username
    ENV['AUTH_USERNAME']
  end

  def username?
    !!username
  end

  def password
    ENV['AUTH_PASSWORD']
  end

  def password?
    !!password
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  include Gaffe::Errors

  def show
    super
    expires_in(1.minute, public: true)
  end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController

  rescue_from ActionController::ParameterMissing, with: ->{ redirect_to new_user_profile_path }, only: :create

  def new
    @user_profile = UserProfile.new
    @user_profile_regions = [
      ['North East', :north_east],
      ['North West', :north_west],
      ['Yorkshire and the Humber', :yorkshire_and_the_humber],
      ['East Midlands', :east_midlands],
      ['West Midlands', :west_midlands],
      ['East of England', :east_of_england],
      ['London', :london],
      ['South East', :south_east],
      ['South West', :south_west],
      ['Wales', :wales],
      ['Scotland', :scotland],
      ['Northern Ireland', :northern_ireland]
    ]

    expires_in(10.minutes, public: true)
  end

  def create
    UserProfile.create(user_profile_params)

    render :confirmation
  end

private

  def user_profile_params
    params
      .require(:user_profile)
      .permit(:email, :phone, :name, :age, :region, :retirement_preference, :pension_type, :channel_preference_web,
              :channel_preference_phone, :channel_preference_face_to_face, :wishlist)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<% content_for :head do %>
  <!--[if gt IE 8]><!--><%= stylesheet_link_tag 'register-your-interest', media: 'screen' %><!--<![endif]-->
  <!--[if IE 6]><%= stylesheet_link_tag 'register-your-interest-ie6', media: 'screen' %><![endif]-->
  <!--[if IE 7]><%= stylesheet_link_tag 'register-your-interest-ie7', media: 'screen' %><![endif]-->
  <!--[if IE 8]><%= stylesheet_link_tag 'register-your-interest-ie8', media: 'screen' %><![endif]-->
<% end %>

<% content_for :body_start do %>
  <!-- Google Tag Manager -->
  <noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-5BW7TX"
                    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      '//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-5BW7TX');</script>
  <!-- End Google Tag Manager -->
<% end %>

<% content_for :content do %>
  <div class="l-masthead">
    <div class="l-banner-container">
      <%= render 'components/phase_banner' %>
      <%= render 'components/logo_link' %>
    </div>
  </div>

  <div class="l-page-container">
    <%= render 'components/breadcrumbs' %>

    <div class="l-grid-row">
      <div class="l-column-two-thirds">
        <main role="main" id="content" tabindex="-1">
          <article role="article" class="l-text">
            <%= content_for?(:article) ? yield(:article) : yield %>
          </article>
        </main>
      </div>
      <div class="l-column-third l-column-third--sidebar">
        <div class="sidebar-hr"></div>
        <%= yield :sidebar %>
      </div>
    </div>

  </div>
<% end %>

<% content_for :body_end do %>
  <%= javascript_include_tag 'register-your-interest' %>
<% end %>

<%= render template: 'layouts/govuk_template' %>

app/views/layouts/error.html.erb
<%= content_for :article do %>
  <div class="text">
    <%= yield %>
  </div>
<% end %>

<%= render template: 'layouts/application' %>

app/views/user_profiles/confirmation.html.erb
<% content_for :page_title, 'Thank you for your interest in Pension Wise - GOV.UK' %>

<div class="text">
  <h1 class="heading-xlarge">Thank you for your interest in Pension Wise.</h1>

  <p>We’ll contact you with more details in the near future.</p>

  <p>Do not reply to suspicious emails. Our service will never ask you for your bank details or to buy a product.</p>
</div>

app/views/user_profiles/new.html.erb
<% content_for :page_title, 'Register your interest in Pension Wise guidance appointments - GOV.UK' %>

<div class="text">
  <h1 class="heading-xlarge">Register your interest in Pension Wise guidance appointments</h1>

  <p>You’ll soon be able to book a free appointment with a trained guidance specialist. Appointments are over the phone
    or face to face with guidance specialists from The Pensions Advisory Service and the Citizens Advice service.</p>

  <p>You’ll discuss:</p>

  <ul class="list-bullet">
    <li>
      the different ways you can take money from your pension pot(s)
    </li>
    <li>
      what each option means for you and your circumstances
    </li>
    <li>
      what to do once you’ve made your choice
    </li>
  </ul>

  <p>This is an impartial government service - Pension Wise won’t recommend any products or tell you what to do with
    your money.</p>

  <p>Complete this form to register your interest in early access to the appointments. If you’ve already completed
    this form you don’t need to re-register.</p>
</div>

<%= form_for @user_profile, url: user_profile_path, authenticity_token: false, class: 'form' do |f| %>

  <div class="form-group">
    <%= f.label :name, 'Name', class: 'form-label-bold' %>
    <%= f.text_field :name, class: %w(t-name form-control) %>
  </div>

  <div class="form-group">
    <%= f.label :age, class: 'form-label-bold' %>
    <%= f.number_field :age, class: %w(t-age form-control form-control-1-8) %>
  </div>

  <div class="form-group">
    <%= f.label :email, class: 'form-label-bold' %>
    <%= f.email_field :email, class: %w(t-email form-control) %>
  </div>

  <div class="form-group">
    <%= f.label :phone, 'Phone number', class: 'form-label-bold' %>
    <%= f.text_field :phone, class: %w(t-phone form-control) %>
  </div>

  <div class="form-group">
    <%= f.label :region, class: 'form-label-bold' %>
    <%= f.select :region, @user_profile_regions, { prompt: '- Select region -' }, { class: %w(t-region) } %>
  </div>

  <div class="form-group">
    <fieldset>
      <legend class="form-label-bold">When do you plan to retire?</legend>

      <%= f.label :retirement_preference_6_months, class: 'block-label' do %>
        <%= f.radio_button :retirement_preference, '6_months',
                           class: 't-retirement_preference_6_months' %>
        In the next 6 months
      <% end %>

      <%= f.label :retirement_preference_6_to_12_months, class: 'block-label' do %>
        <%= f.radio_button :retirement_preference, '6_to_12_months',
                           class: 't-retirement_preference_6_to_12_months' %>
        In the next 6 to 12 months
      <% end %>

      <%= f.label :retirement_preference_1_to_5_years, class: 'block-label' do %>
        <%= f.radio_button :retirement_preference, '1_to_5_years',
                           class: 't-retirement_preference_1_to_5_years' %>
        In the next 1 to 5 years
      <% end %>

      <%= f.label :retirement_preference_more_than_5_years, class: 'block-label' do %>
        <%= f.radio_button :retirement_preference, 'more_than_5_years',
                           class: 't-retirement_preference_more_than_5_years' %>
        More than 5 years
      <% end %>

      <%= f.label :retirement_preference_retired, class: 'block-label' do %>
        <%= f.radio_button :retirement_preference, 'retired',
                           class: 't-retirement_preference_retired' %>
        I'm already retired
      <% end %>

      <%= f.label :retirement_preference_unknown, class: 'block-label' do %>
        <%= f.radio_button :retirement_preference, 'unknown',
                           class: 't-retirement_preference_unknown' %>
        I don’t know
      <% end %>
    </fieldset>
  </div>

  <div class="form-group">
    <fieldset>
      <legend class="form-label-bold">What type of pension do you have?</legend>

      <%= f.label :pension_type_defined_contribution, class: 'block-label' do %>
        <%= f.radio_button :pension_type, 'defined_contribution',
                           class: 't-pension_type_defined_contribution' %>
        A defined contribution pension - one based on how much money has been paid into your pot
      <% end %>

      <%= f.label :pension_type_defined_benefit, class: 'block-label' do %>
        <%= f.radio_button :pension_type, 'defined_benefit',
                           class: 't-pension_type_defined_benefit' %>
        A defined benefit pension - one based on your salary and length of time with your employer
      <% end %>

      <%= f.label :pension_type_both, class: 'block-label' do %>
        <%= f.radio_button :pension_type, 'both',
                           class: 't-pension_type_both' %>
        Both
      <% end %>

      <%= f.label :pension_type_unknown, class: 'block-label' do %>
        <%= f.radio_button :pension_type, 'unknown',
                           class: 't-pension_type_unknown' %>
        I don’t know
      <% end %>
    </fieldset>
  </div>

  <div class="form-group">
    <fieldset>
      <legend class="form-label-bold">What kind of appointment would you prefer?</legend>

      <%= hidden_field_tag 'user_profile[channel_preference_phone]', 0, id: nil %>
      <%= f.label :channel_preference_phone, class: 'block-label' do %>
        <%= check_box_tag 'user_profile[channel_preference_phone]', 1,
                          @user_profile.channel_preference_phone,
                          class: 't-channel_preference_phone' %>

        Over the phone
      <% end %>

      <%= hidden_field_tag 'user_profile[channel_preference_face_to_face]', 0, id: nil %>
      <%= f.label :channel_preference_face_to_face, class: 'block-label' do %>
        <%= check_box_tag 'user_profile[channel_preference_face_to_face]', 1,
                          @user_profile.channel_preference_face_to_face,
                          class: 't-channel_preference_face_to_face' %>

        Face to face
      <% end %>
    </fieldset>
  </div>

  <div class="form-group">
    <%= f.label :wishlist, 'What would you like to get from the appointment?', class: 'form-label-bold' %>
    <%= f.text_area :wishlist, class: %w(t-wishlist form-control), rows: '8' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Submit', class: %w(t-submit button) %>
  </div>

<% end %>